server:
  port: 8081

spring:
  data:
    mongodb:
      database: customerDB
      host: localhost
      port: 27017
  application:
    name: CUSTOMER-SERVICE

#Actuator
management:
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include: health, info, refresh, restart, env
  endpoint:
    health:
      enabled: true
    info:
      enabled: true
    refresh:
      enabled: true
    restart:
      enabled: true
    env:
      enabled: true
