server:
  port: 8081

spring:
  data:
    mongodb:
      database: customerDB
      host: mongoDB
      port: 27017

#Actuator
management:
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include: health, info, refresh, restart, env
  endpoint:
    health:
      enabled: true
    info:
      enabled: true
    refresh:
      enabled: true
    restart:
      enabled: true
    env:
      enabled: true
      

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server-service:8761/eureka

