server:
  port: 8082

spring:
  data:
    mongodb:
      database: transactionBD
      host: localhost
      port: 27017
  application:
    name: TRANSACTION-SERVICE

#Variables - dev
application:
  location: config (gitHub) - Enviroment DEV
  operation:
    DEPOSITO: DEPOSITO
    RETIRO: RETIRO
    
#Actuator - dev
management:
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include: health, info, refresh, restart, env
  endpoint:
    health:
      enabled: true
    info:
      enabled: true
    refresh:
      enabled: true
    restart:
      enabled: true
    env:
      enabled: true
