server:
  port: 8082

spring:
  data:
    mongodb:
      database: transactionBD
      host: localhost
      port: 27017
  application:
    name: TRANSACTION-SERVICE
    
#Variables - QA
application:
  location: config (GITHUB) QA
  config:
    profile: qa
    description: enviroment dev from transaction-service-qa.yml
    
  operation:
    DEPOSITO: DEPOSITO
    RETIRO: RETIRO

#Actuator QA
management:
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include: health, info, refresh, restart, env
  endpoint:
    health:
      enabled: true
    info:
      enabled: true
    refresh:
      enabled: true
    restart:
      enabled: true
    env:
      enabled: true
