server:
  port: 8082

spring:
  data:
    mongodb:
      database: transactionBD
      host: mongoDB
      port: 27017


#Actuator - dev
management:
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include: health, info, refresh, restart, env
  endpoint:
    health:
      enabled: true
    info:
      enabled: true
    refresh:
      enabled: true
    restart:
      enabled: true
    env:
      enabled: true


eureka:
  client:
    service-url:
      defaultZone: http://eureka-server-service:8761/eureka

spring:
  kafka:
    producer:
      bootstrap-servers: kafka:9093
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

kafka:
  topic: topic-demo


#Variables - dev
application:
  location: config (GITHUB) DEV
  config:
    profile: dev
    description: enviroment dev from transaction-service-dev.yml - REFRESH REFRESH
    
  operation:
    deposit: DEPOSITO
    retirement: RETIRO
    payment: PAGO
    consumption: CONSUMO
    numberOperationAllowed: 4
    commision: 40.00
