server:
  port: 8082

spring:
  data:
    mongodb:
      database: transactionBD
      host: localhost
      port: 27018
  application:
    name: TRANSACTION-SERVICE

#Actuator - dev
management:
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include: health, info, refresh, restart, env
  endpoint:
    health:
      enabled: true
    info:
      enabled: true
    refresh:
      enabled: true
    restart:
      enabled: true
    env:
      enabled: true
  
#Variables - dev
application:
  location: config (GITHUB) DEV
  config:
    profile: dev
    description: enviroment dev from transaction-service-dev.yml - REFRESH ACTUATOR
    
  operation:
    deposit: DEPOSITO
    retirement: RETIRO
    payment: PAGO
    consumption: CONSUMO
    numberOperationAllowed: 4
    commision: 30.00
